# NOTE: The below 2 variables should not need to be changed if you cloned
#       the dotfiles repo to '~/.dotfiles'
# Home directory
dotfiles_user_home: "{{ '~' | expanduser }}"
# Where your dotfiles live. Probably don't need to change this.
dotfiles_home: "{{dotfiles_user_home}}/.dotfiles"

# Name used in commit messages
full_name: Rishi Dhupar

# Git
# Github username
github_user: rishid
# If you use github, this should be the same as the email
#  used on Github
github_email: rishid@gmail.com


go:
  path: ~/Go
  default_version: 1.4.2
  versions:
    - 1.4.2
  packages:
    - github.com/nsf/gocode


packages:
  - coreutils
  - dos2unix
  - expect
  - htop
  - iftop
  - jq
  - keychain
  - meld
  - openssh-server
  - pv
  - python
  - python3-pip
  - silversearcher-ag
  - speedtest-cli
  - tree
  - wget

remove_packages:

pip_packages:
  httpie:
  httpie-oauth:
  httpie-http2:
  httpie-ntlm:
  httpie-jwt-auth:
  request:

docker_users:
  - "{{ localuser }}"
