
- name: Update apt cache
  apt: update_cache=yes
  when: package_update
  become: yes
  tags: update

- name: Upgrade apt packages
  apt: upgrade=yes
  when: package_upgrade
  become: yes
  tags: update

- name: Install base apt packages
  apt:
    pkg: "{{ packages }}"
    state: latest
  become: yes
  tags: update
