function ssh-key-help
    echo "SSH Key Management Commands:"
    echo "  ssh-key-add <path>     - Add a key to the agent and optionally to ~/.ssh/autoload"
    echo "  ssh-key-remove <path>  - Remove a key from the agent and optionally from ~/.ssh/autoload"
    echo "  ssh-key-list           - List loaded keys and auto-load configuration"
    echo "  ssh-agent-status       - Show ssh-agent service status and loaded keys"
    echo "  ssh-agent-restart      - Restart the ssh-agent service and reload keys"
    echo "  ssh-key-help           - Show this help message"
    echo ""
    echo "Configuration:"
    echo "  ~/.ssh/autoload - Single source of truth for SSH key auto-loading"
    echo "  List one SSH private key path per line (use ~ for home directory)"
    echo "  Lines starting with # are ignored (comments)"
    echo ""
    echo "Examples:"
    echo "  ssh-key-add ~/.ssh/id_rsa"
    echo "  ssh-key-add ~/.ssh/github_akamai"
    echo "  echo '~/.ssh/work_key' >> ~/.ssh/autoload"
    echo "  echo '# ~/.ssh/old_key' >> ~/.ssh/autoload  # commented out"
end
