---
fail_fast: false
ci:
  autofix_commit_msg: |
    [pre-commit.ci] Auto fixes from pre-commit.com hooks
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  submodules: false

repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        name: "YAML: lint"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: check-added-large-files
        args: [--maxkb=2048]
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-yaml
      - id: file-contents-sorter
        files: "^(tilde/private_dot_config/fish/fish_plugins)$"

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: forbid-crlf

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
