extends: default

yaml-files:
  - '*.yaml'
  - '*.yaml.tmpl'
  - '*.yml'
  - '*.yml.tmpl'
  - '.yamllint'

rules:
  braces:
    max-spaces-inside: 1
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  document-start: disable
  line-length:
    max: 100
    level: warning
  indentation:
    level: warning
  truthy:
    check-keys: false
