#!/usr/bin/env python
# encoding: utf-8

from os import environ, listdir
from os.path import dirname, exists, expanduser, join, realpath
from subprocess import call
import sys
from time import sleep


def ask_yn(question):
    question += ' (y/n)  '
    answer = None

    while answer not in ['yes', 'y', 'no', 'n']:
        answer = raw_input(question).lower()

    return answer.startswith('y')

def run(command):
    return call(command, shell=True)

def _main():
    # get dotfiles directory
    dotfiles_dir = dirname(realpath(__file__))

    # run installer
    installer_path = join(dotfiles_dir, 'installer/installer.py')
    run('python ' + installer_path)

    # "install" git submodules
    print '\n\n"installing" git submodules...'
    sys.stdout.flush()
    sleep(2)
    run(' && '.join(['cd ' + dotfiles_dir,
                     'git submodule init',
                     'git submodule update']))


    # tell how to switch to zsh
    shell = environ.get('SHELL')
    if not shell or not shell.endswith('zsh'):
        print ' -  run "chsh -s `which zsh` $USER" to switch to zsh ' \
              '(you may need to relog)'

if __name__ == '__main__':
    _main()
