---

- name: Install OpenSSH server
  apt:
    name: openssh-server
    state: latest
    install_recommends: False
  notify:
    - test and restart sshd
  tags: bootstrap

- name: Disable password authentication for root
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin prohibit-password'

- name: UFW - Allow SSH connections
  ufw:
    rule: allow
    name: OpenSSH

- name: UFW - Deny all other incoming traffic by default
  ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: Enable Workspaces span displays
  command: gsettings set org.gnome.mutter workspaces-only-on-primary false
  changed_when: False

- name: Disable dynamic workspaces
  command: gsettings set org.gnome.mutter dynamic-workspaces false
  changed_when: False

- name: Set static workspaces
  command: gsettings set org.gnome.desktop.wm.preferences num-workspaces 4
  changed_when: False


