---
- name: ensure .ssh directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
    mode: 0700
    state: directory

- name: write out public keys
  when: mtype == 'personal'
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.ssh/{{ item }}.pub"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
    mode: 0600
    src: keys/{{ item }}.pub
  loop: "{{ ssh_keys }}"

- name: write out private keys
  when: mtype == 'personal'
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.ssh/{{ item }}"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
    mode: 0600
    src: keys/{{ item }}
  loop: "{{ ssh_keys }}"

- name: write out public key
  when: mtype == 'work'
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.ssh/id_rsa.pub"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
    mode: 0600
    src: keys/work.pub

- name: write out private key
  when: mtype == 'work'
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.ssh/id_rsa"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
    mode: 0600
    src: keys/work

# https://serverfault.com/a/599565
- name: write out ssh pub keys for forwarding
  when: mtype == 'server' and wedition == 'personal'
  ansible.builtin.shell:
    cmd: ssh-add -L | grep '!{{ item }}$' > {{ ansible_user_dir }}/.ssh/{{ item }}.pub
    creates: "{{ ansible_user_dir }}/.ssh/{{ item }}.pub"
  loop:
    - arch
    - github

- name: install ssh config
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.ssh/config"
    owner: "{{ whoami }}"
    group: "{{ whoami_group }}"
    mode: 0600
    src: config.j2
