---
# Name used in commit messages
full_name: Rishi Dhupar

# Git
github_user: rishid
github_email: rishid@gmail.com

apt:
  install:
    - build-essential
    - clang
    - cmake
    - coreutils
    - default-jre
    - dos2unix
    - expect
    - git
    - graphviz
    - htop
    - iftop
    - jq
    - keychain
    - libssl-dev
    - meld
    - openssh-server
    - pv
    - python3
    - python3-pip
    - silversearcher-ag
    - socat
    - speedtest-cli
    - tree
    - wget
  remove:

pip:
  install:
    - pandas
    - pre-commit
    - requests
    - yq
    - chepy
  remove:
    - pyOpenSSL

plugins:
  vscode:
    ### code
    - "bierner.github-markdown-preview"
    ### tools
    - "eamodio.gitlens"

versions:
  age: "1.2.1" # renovate: depName=FiloSottile/age
  backstage_go: "0.9.0" # renovate: depName=einride/backstage-go
  bat: "0.25.0" # renovate: depName=sharkdp/bat versioning=semver-coerced
  cloc: "1.96" # renovate: depName=AlDanial/cloc
  direnv: "2.35.0" # renovate: depName=direnv/direnv
  dnspyre: "3.5.0" # renovate: depName=Tantalor93/dnspyre
  gdu: "5.30.1" # renovate: depName=dundee/gdu
  github_cli: "2.67.0" # renovate: depName=cli/cli
  fd: "10.2.0" # renovate: depName=sharkdp/fd
  fzf: "0.60.1" # renovate: depName=junegunn/fzf
  helm: "3.17.1" # renovate: depName=helm/helm
  kubectl: "1.32.2" # renovate: depName=kubernetes/kubernetes
  kustomize: "v5.1.1" # renovate: depName=kubernetes-sigs/kustomize
  procs: "0.14.9" # renovate: depName=dalance/procs
  ripgrep: "14.1.1" # renovate: depName=BurntSushi/ripgrep
  starship: "1.22.1" # renovate: depName=starship/starship
  trivy: "0.59.1" # renovate: depName=aquasecurity/trivy
  yq: "4.45.1" # renovate: depName=mikefarah/yq
