---
# Name used in commit messages
full_name: Rishi Dhupar

# Git
github_user: rishid
github_email: rishid@gmail.com

apt:
  install:
    - build-essential
    - clang
    - cmake
    - coreutils
    - default-jre
    - dos2unix
    - expect
    - git
    - graphviz
    - htop
    - iftop
    - jq
    - keychain
    - libssl-dev
    - meld
    - openssh-server
    - pv
    - python
    - python3-pip
    - silversearcher-ag
    - socat
    - speedtest-cli
    - tree
    - wget
  remove:

pip:
  install:
    - pre-commit
    - requests
    - yq
    - chepy
  remove:
    - pyOpenSSL

plugins:
  vscode:
    ### code
    - "bierner.github-markdown-preview"
    ### tools
    - "eamodio.gitlens"

versions:
  age: "1.1.1" # renovate: depName=FiloSottile/age
  backstage_go: "v0.8.0" # renovate: depName=einride/backstage-go
  bat: "0.24.0" # renovate: depName=sharkdp/bat versioning=semver-coerced
  cloc: "1.96" # renovate: depName=AlDanial/cloc
  direnv: "2.34.0" # renovate: depName=direnv/direnv
  gdu: "5.28.0" # renovate: depName=dundee/gdu
  github_cli: "2.50.0" # renovate: depName=cli/cli
  fd: "10.1.0" # renovate: depName=sharkdp/fd
  fzf: "0.52.1" # renovate: depName=junegunn/fzf
  helm: "3.15.1" # renovate: depName=helm/helm
  kubectl: "1.30.1" # renovate: depName=kubernetes/kubernetes
  kustomize: "v5.1.1" # renovate: depName=kubernetes-sigs/kustomize
  procs: "0.14.5" # renovate: depName=dalance/procs
  ripgrep: "14.1.0" # renovate: depName=BurntSushi/ripgrep
  starship: "1.19.0" # renovate: depName=starship/starship
  trivy: "0.52.0" # renovate: depName=aquasecurity/trivy
  yq: "4.44.1" # renovate: depName=mikefarah/yq
