---
# Name used in commit messages
full_name: Rishi Dhupar

# Git
github_user: rishid
github_email: rishid@gmail.com

apt:
  install:
    # Essential system packages only
    - git                 # Required for chezmoi and version control
    - curl                # Required for downloads and scripts
    - wget                # Basic download utility
    - build-essential     # Compilers for building some packages
    - openssh-server      # SSH server (system service)
    - tree                # Directory listing utility
    - htop                # System monitoring
    - jq                  # JSON processor (used in many scripts)
    - keychain            # SSH key management (system integration)

    # Optional system utilities
    - dos2unix            # Text file conversion
    - socat               # Network utility
    - pv                  # Progress viewer
    - meld                # GUI diff tool
    - speedtest-cli       # Network testing

  remove: []

plugins:
  vscode:
    ### code
    - "bierner.github-markdown-preview"
    ### tools
    - "eamodio.gitlens"
