---
# Name used in commit messages
full_name: Rishi Dhupar

# Git
github_user: rishid
github_email: rishid@gmail.com

apt:
  install:
    - build-essential
    - clang
    - cmake
    - coreutils
    - default-jre
    - dos2unix
    - expect
    - git
    - graphviz
    - htop
    - iftop
    - jq
    - keychain
    - libssl-dev
    - meld
    - openssh-server
    - pv
    - python3
    - python3-pip
    - silversearcher-ag
    - socat
    - speedtest-cli
    - tree
    - wget
  remove:

pip:
  install:
    - pandas
    - pre-commit
    - requests
    - yq
    - chepy
  remove:
    - pyOpenSSL

plugins:
  vscode:
    ### code
    - "bierner.github-markdown-preview"
    ### tools
    - "eamodio.gitlens"

versions:
  age: "1.2.1" # renovate: depName=FiloSottile/age
  backstage_go: "0.9.0" # renovate: depName=einride/backstage-go
  bat: "0.25.0" # renovate: depName=sharkdp/bat versioning=semver-coerced
  cloc: "1.96" # renovate: depName=AlDanial/cloc
  direnv: "2.36.0" # renovate: depName=direnv/direnv
  dnspyre: "3.5.1" # renovate: depName=Tantalor93/dnspyre
  gdu: "5.31.0" # renovate: depName=dundee/gdu
  github_cli: "2.74.0" # renovate: depName=cli/cli
  go: "1.17.2" # renovate: depName=golang/go
  fd: "10.2.0" # renovate: depName=sharkdp/fd
  fzf: "0.62.0" # renovate: depName=junegunn/fzf
  helm: "3.18.2" # renovate: depName=helm/helm
  hexyl: "0.16.0" # renovate: depName=sharkdp/hexyl
  hyperfine: "1.19.0" # renovate: depName=sharkdp/hyperfine
  numbat: "1.16.0" # renovate: depName=sharkdp/numbat
  kubectl: "1.33.1" # renovate: depName=kubernetes/kubernetes
  procs: "0.14.10" # renovate: depName=dalance/procs
  ripgrep: "14.1.1" # renovate: depName=BurntSushi/ripgrep
  starship: "1.23.0" # renovate: depName=starship/starship
  task: "3.44.0" # renovate: depName=go-task/task
  trivy: "0.63.0" # renovate: depName=aquasecurity/trivy
  yq: "4.45.4" # renovate: depName=mikefarah/yq
  zoxide: "0.9.8" # renovate: depName=ajeetdsouza/zoxide
