---
# - name: Ensure Stow installed
#   become: true
#   ansible.builtin.apt:
#     name: stow
#     cache_valid_time: 3600

# - name: Build directories list
#   ansible.builtin.find:
#     paths: 
#       - "{{ dotfiles }}"
#     recurse: no
#     file_type: directory
#   register: files

# - name: Print return information from the previous task
#   ansible.builtin.debug:
#     var: files

- name: Install chezmoi using a package
  ansible.builtin.import_tasks: download-chezmoi.yml

- name: Initialize chezmoi
  ansible.builtin.command: "chezmoi init --guess-repo-url false --source-path {{ dotfiles_home }} --apply --verbose {{ dotfiles_repo }}"
  when: dotfiles_repo
  args:
    creates: "~/.local/share/chezmoi"
