
- import_tasks: mac.yml
  when: ansible_os_family == "Darwin"
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Link global gitignore file
  file:
    src: "{{ dotfiles_home }}/roles/git/files/gitignore.link"
    dest: "{{ dotfiles_user_home }}/.gitignore"
    state: link
    force: yes

- name: Back up gitconfig
  copy: 
    src: "{{ git_config_path }}"
    dest: "{{ dotfiles_user_home }}/.gitconfig.bak"
  when: git_config_path is file

- name: Link global gitconfig file
  file:
    src: "{{ dotfiles_home }}/roles/git/files/gitconfig.link"
    dest: git_config_path
    state: link
    force: yes
