- name: Set up local workstation
  hosts: local
  gather_facts: true
  vars:
    localuser: "{{ lookup('env','USER') }}"

  pre_tasks:
    - debug: msg=pre_task

  roles:
    # Tag each role so that we can select individual roles to run with ansible-playbook --tags
    - { role: git, tags: ['git'] }

    - role: package_manager
      tags:
        - 'package_manager'
      become: true

    - role: ubuntu
      when: ansible_os_family == "Debian"
      tags:
        - 'ubuntu'
      become: true


    - { role: dotfiles, tags: ['dotfiles'] }
    # - { role: bash,     tags: ['bash'] }
    # - { role: emacs,    tags: ['emacs'] }
    # - { role: tmux,     tags: ['tmux'] }

    # - role: borg
    #  tags: ['borg', 'bootstrap']
    #  when: ansible_os_family == "Debian"
    #  become: True
