
- name: Update apt cache
  apt: update_cache=yes
  when: package_update
  tags: update

- name: Upgrade apt packages
  apt: upgrade=yes
  when: package_upgrade
  tags: update

- name: Install base apt packages
  apt:
    pkg: "{{ packages }}"
    state: latest
  tags: update
