---
# - name: Clone Spacemacs
#   git: >
#     repo=git://github.com/syl20bnr/spacemacs.git
#     dest=~/.emacs.d
#     force=no
#     refspec=develop

# - name: Clone my spacemacs.d
#   git: >
#     repo=git@github.com:rishid/spacemacs.d.git
#     dest=~/.spacemacs.d
#     force=no
#   tags: update


- name: Check if emacs.d exists
  stat: path="{{dotfiles_user_home}}/.emacs.d"
  register: emacsd_stat

- name: Back up emacs.d
  command: mv ~/.emacs.d ~/.emacs.d.bak
  args:
    creates: "{{ dotfiles_user_home }}/.emacs.d.bak"
  when: emacsd_stat.stat.exists

- name: Link .emacs.d
  file:
    src: "{{ dotfiles_home }}/roles/emacs/files/emacs.d"
    dest: "{{ dotfiles_user_home }}/.emacs.d"
    state: link
    force: yes
  when: ansible_os_family != "Darwin"
